--------------------------------------------------------
--  File created - Tuesday-August-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BORROWER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BEARSHARK"."BORROWER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LENDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BEARSHARK"."LENDER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BORROWER
--------------------------------------------------------

  CREATE TABLE "BEARSHARK"."BORROWER" 
   (	"BORROWER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"CREDIT_SCORE" NUMBER, 
	"ZIP_CODE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LENDERS
--------------------------------------------------------

  CREATE TABLE "BEARSHARK"."LENDERS" 
   (	"LENDER_ID" NUMBER, 
	"LENDER_NAME" VARCHAR2(20 BYTE), 
	"LENDER_ZIPCODE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOANS
--------------------------------------------------------

  CREATE TABLE "BEARSHARK"."LOANS" 
   (	"LOAN_ID" NUMBER, 
	"LOAN_APR" NUMBER(5,4), 
	"LOAN_PRINCIPAL" NUMBER, 
	"LOAN_START_DATE" DATE, 
	"LOAN_LAST_UPDATE" DATE, 
	"LOAN_IS_ADJUSTABLE" NUMBER(1,0), 
	"BORROWER_ID" NUMBER, 
	"LENDER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POOLS
--------------------------------------------------------

  CREATE TABLE "BEARSHARK"."POOLS" 
   (	"POOL_ID" NUMBER, 
	"INITIAL_TOTAL" NUMBER, 
	"INITIAL_APR" NUMBER(5,4), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POOL_LOANS
--------------------------------------------------------

  CREATE TABLE "BEARSHARK"."POOL_LOANS" 
   (	"LOAN_ID" NUMBER, 
	"POOL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BEARSHARK.BORROWER
SET DEFINE OFF;
REM INSERTING into BEARSHARK.LENDERS
SET DEFINE OFF;
REM INSERTING into BEARSHARK.LOANS
SET DEFINE OFF;
REM INSERTING into BEARSHARK.POOLS
SET DEFINE OFF;
REM INSERTING into BEARSHARK.POOL_LOANS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BORROWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BEARSHARK"."BORROWER_PK" ON "BEARSHARK"."BORROWER" ("BORROWER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BEARSHARK"."ID_PK" ON "BEARSHARK"."LOANS" ("LOAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LEND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BEARSHARK"."LEND_PK" ON "BEARSHARK"."LENDERS" ("LENDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOAN_POOL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BEARSHARK"."LOAN_POOL_PK" ON "BEARSHARK"."POOL_LOANS" ("LOAN_ID", "POOL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POOLS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BEARSHARK"."POOLS_PK" ON "BEARSHARK"."POOLS" ("POOL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BORROWER
--------------------------------------------------------

  ALTER TABLE "BEARSHARK"."BORROWER" ADD CONSTRAINT "BORROWER_PK" PRIMARY KEY ("BORROWER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LENDERS
--------------------------------------------------------

  ALTER TABLE "BEARSHARK"."LENDERS" ADD CONSTRAINT "LEND_PK" PRIMARY KEY ("LENDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOANS
--------------------------------------------------------

  ALTER TABLE "BEARSHARK"."LOANS" ADD CONSTRAINT "ID_PK" PRIMARY KEY ("LOAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POOLS
--------------------------------------------------------

  ALTER TABLE "BEARSHARK"."POOLS" ADD CONSTRAINT "POOLS_PK" PRIMARY KEY ("POOL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POOL_LOANS
--------------------------------------------------------

  ALTER TABLE "BEARSHARK"."POOL_LOANS" ADD CONSTRAINT "LOAN_POOL_PK" PRIMARY KEY ("LOAN_ID", "POOL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOANS
--------------------------------------------------------

  ALTER TABLE "BEARSHARK"."LOANS" ADD CONSTRAINT "LEND_FK" FOREIGN KEY ("LENDER_ID")
	  REFERENCES "BEARSHARK"."LENDERS" ("LENDER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POOL_LOANS
--------------------------------------------------------

  ALTER TABLE "BEARSHARK"."POOL_LOANS" ADD CONSTRAINT "LOAN_FK" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "BEARSHARK"."LOANS" ("LOAN_ID") ENABLE;
  ALTER TABLE "BEARSHARK"."POOL_LOANS" ADD CONSTRAINT "POOL_FK" FOREIGN KEY ("POOL_ID")
	  REFERENCES "BEARSHARK"."POOLS" ("POOL_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BORROWER_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BEARSHARK"."BORROWER_TRIG" 
  before insert on borrower
  for each row
  begin
    select borrower_seq.nextval into :new.borrower_id from dual;
  end;
/
ALTER TRIGGER "BEARSHARK"."BORROWER_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LENDER_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BEARSHARK"."LENDER_TRIG" 
  before insert on lenders
  for each row
  begin
    select lender_seq.nextval into :new.lender_id from dual;
  end; --


  create sequence pools_seq
  start with 1
  increment by 1; --

create or replace trigger pools_trig
  before insert on pools
  for each row
  begin
    select pools_seq.nextval into :new.pool_id from dual;
  end; --

 create sequence Loans_seq
start with 1 
increment by 1;
--
create or replace trigger Loan_trig
before insert on Loans
for each row begin 
select Loans_seq.nextval into :new.Loan_ID from dual;
end; --
/
ALTER TRIGGER "BEARSHARK"."LENDER_TRIG" ENABLE;
