
<div id="ViewPoolModal" class="modal fade" role="dialog">
	<div class="modal-admin">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">View Pool</h4>
			</div>
			<div class="modal-body" id="view_pool_modal_body">
				<!-- This content is generated by JavaScript. -->
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
